- ( **1** ) _Importing numpy_

In [164]:
import numpy as np

---

<br>
<br>

### **_Create Array_**

- ( **2** ) _Create an array that contains numbers from 1 to 10._

In [165]:
num1to10 = np.array([1,2,3,4,5,6,7,8,9,10])
num1to10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<br>

In [166]:
num1to10 = np.arange(1,11)
num1to10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---

<br>

- ( **3** ) _Create the following array._<br>

```[[15, 12, 9, 22],```<br>
```[21, 7, 10, 14], ```<br>
```[31, 10, 33, 8]] ```<br>

In [167]:
copy = np.array([[15, 12, 9, 22],[21, 7, 10, 14], [31, 10, 33, 8]])
copy

array([[15, 12,  9, 22],
       [21,  7, 10, 14],
       [31, 10, 33,  8]])

---

<br>

- ( **4** ) _Create an array full of zeros and of shape (2,3)._


    Solution 1

In [168]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

<br>

    Solution 2

In [169]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.zeros_like(a)
print()
print(b)

[[1 2 3]
 [4 5 6]]

[[0 0 0]
 [0 0 0]]


---

<br>

- ( **5** ) Create an array that contains odd numbers from 1 to 1000.

In [170]:
array1to1000 = np.arange(1,1001)
odd1to1000 = array1to1000[array1to1000 % 2 == 1]
#print(odd1to1000)

---

<br>
<br>

### **_Array Details_**

- ( **6** ) _Making a 3D array_

In [171]:
a3d = np.ones((2,2,2))
a3d = a3d.astype(int)
print(a3d)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


---

<br>

- ( **7** ) _Show dimension._

In [172]:
print(a3d.ndim)

3


---

<br>



- ( **8** ) _What is the difference between shape and size?_<br>
    > Explain with words and with code.


    - Shape: returns a tuple representing the dimensions of the array. For example, an array with 3 rows and 4 columns would have a shape of (3, 4).<br>

    - Size: returns the total number of elements in the array. In the above example, the size of the array would be 12.

In [173]:
# Create a 2D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Print the shape of the array
print("Shape of array:", arr.shape)

# Print the size of the array
print("Size of array:", arr.size)

Shape of array: (3, 4)
Size of array: 12


---

<br>
<br>


### **_Indexing & Slicing_**

- ( **9** ) _Get the value of the element in the first row and second column._

In [174]:
np.random.seed(42)
arr = np.random.randn(3, 3)

    Solution

In [175]:
print(arr,"\n")
print(arr[(0,1)])

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]] 

-0.13826430117118466


---

<br>

- ( **10** ) _Get the first 2 rows._

In [176]:
np.random.seed(42)
arr = np.random.randn(3, 3)

    Solution

In [177]:
print(arr,"\n")
print(arr[0:2])

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]] 

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]]


---

<br>

- ( **11** ) _Change the shape of the array to be (2, 6) and print the new shape._

In [178]:
np.random.seed(42)
arr = np.random.randn(4, 3)

    Solution

In [179]:
print(arr,"\n")
arr.reshape(2,6)

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]] 



array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
        -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439,  0.54256004, -0.46341769,
        -0.46572975]])

---

<br>
<br>

### **_NumPy common functions_**

- ( **12** ) _Flat the following array._

In [180]:
arr = np.array([[i, 2*i, 3*i] for i in range(3, 300)])

    Solution

In [181]:
# Printing first 10 rows of array
print(arr[0:11])

[[ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]
 [ 8 16 24]
 [ 9 18 27]
 [10 20 30]
 [11 22 33]
 [12 24 36]
 [13 26 39]]


In [182]:
# Flattened array
flattened_arr = arr.flatten()

# Printing the first 10 elements of the Flattened array
print(flattened_arr[0:11])

[ 3  6  9  4  8 12  5 10 15  6 12]


    The output is a one-dimensional array containing all the elements of the original array flattened into a single row.

---

<br>
<br>

- ( **13** ) _Transpose the following array._

In [183]:
arr = np.array([[[[j, j + 1] for j in range(5)]] for i in range(3)])

    Solution

In [184]:
print(arr)
print("\nShape: ", arr.shape)

[[[[0 1]
   [1 2]
   [2 3]
   [3 4]
   [4 5]]]


 [[[0 1]
   [1 2]
   [2 3]
   [3 4]
   [4 5]]]


 [[[0 1]
   [1 2]
   [2 3]
   [3 4]
   [4 5]]]]

Shape:  (3, 1, 5, 2)


<br>

    lol, this shape is weird .. lets just transpose it and go to the next question

In [185]:
t_arr = arr.transpose()
print(t_arr)

[[[[0 0 0]]

  [[1 1 1]]

  [[2 2 2]]

  [[3 3 3]]

  [[4 4 4]]]


 [[[1 1 1]]

  [[2 2 2]]

  [[3 3 3]]

  [[4 4 4]]

  [[5 5 5]]]]


---

<br>

- ( **14** ) _How many unique values are in the following array and print them._

In [186]:
countries = np.array(['canada','spain','india','usa','canada','england','japan','germany','india','england','egypt','england','japan','egypt','india','japan'
                     ,'china','germany','india','china','canada','india','canada''egypt','china','germany','japan','russia'
                    ,'england','usa','germany','china','russia''germany''china','spain''spain','canada','germany','spain',
                    'china','canada','china''canada','germany','russia','japan','india','russia','egypt', 'canada',
                    'spain','india','usa','canada','england','japan','germany','india','england','egypt','england','japan',
                    'egypt','india','japan','china','germany','india','china','canada','india','canada''egypt','china','germany','japan','russia'
                      ,'england','usa','germany','china','russia''germany''china','spain''spain','canada','germany','spain',
                      'china','canada','china''canada','germany','russia','japan','india','russia','egypt'])

    Solution 1

In [187]:
print(np.unique(countries))

['canada' 'canadaegypt' 'china' 'chinacanada' 'egypt' 'england' 'germany'
 'india' 'japan' 'russia' 'russiagermanychina' 'spain' 'spainspain' 'usa']


    Solution 2 (Using Python Set)

In [188]:
countries_set = set(countries)
print(countries_set)

{'england', 'egypt', 'russia', 'india', 'germany', 'usa', 'spain', 'japan', 'spainspain', 'canada', 'china', 'canadaegypt', 'russiagermanychina', 'chinacanada'}


---

<br>

- ( **15** ) _Sort the following array._

In [189]:
np.random.seed(42)
arr = np.random.randn(50)

    Solution

In [190]:
print("\narray:\n\n", arr)
print("\n\nSorted array:\n\n", np.sort(arr))


array:

 [ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
  1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769 -0.46572975
  0.24196227 -1.91328024 -1.72491783 -0.56228753 -1.01283112  0.31424733
 -0.90802408 -1.4123037   1.46564877 -0.2257763   0.0675282  -1.42474819
 -0.54438272  0.11092259 -1.15099358  0.37569802 -0.60063869 -0.29169375
 -0.60170661  1.85227818 -0.01349722 -1.05771093  0.82254491 -1.22084365
  0.2088636  -1.95967012 -1.32818605  0.19686124  0.73846658  0.17136828
 -0.11564828 -0.3011037  -1.47852199 -0.71984421 -0.46063877  1.05712223
  0.34361829 -1.76304016]


Sorted array:

 [-1.95967012 -1.91328024 -1.76304016 -1.72491783 -1.47852199 -1.42474819
 -1.4123037  -1.32818605 -1.22084365 -1.15099358 -1.05771093 -1.01283112
 -0.90802408 -0.71984421 -0.60170661 -0.60063869 -0.56228753 -0.54438272
 -0.46947439 -0.46572975 -0.46341769 -0.46063877 -0.3011037  -0.29169375
 -0.23415337 -0.23413696 -0.2257763  -0.1382643  -0.11564828 -0.013497

---

<br>
<br>

### **_Statistics_**

- ( **16** ) _Calculate the following._

In [191]:
np.random.seed(42)
arr = np.random.randn(5,4)
# write your code here
# mean = 
# median = 
# sum =
# variance = 
# std = 

    Solution

In [192]:
print("\narray:\n\n", arr, "\n\nShape:", arr.shape)

print("mean:",np.mean(arr))
print("median:",np.median(arr))
print("sum:",np.sum(arr))
print("variance:",np.var(arr))
print("standeard deviation:",np.std(arr))


array:

 [[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]] 

Shape: (5, 4)
mean: -0.17129856144182892
median: -0.23414516583625827
sum: -3.4259712288365787
variance: 0.8755718414721738
standeard deviation: 0.9357199588937781


---

<br>
<br>

### _**Maths**_

- ( **17** ) _Calculate the following._

In [193]:
np.random.seed(42)
arr = np.random.randn(5, 4)
# max = 
# min = 
# sqrt = 
# abs = 

    Solution
    max and min

In [194]:
print("\narray:\n\n",arr)
print("\nmax:",np.max(arr))
print("min:",np.min(arr))


array:

 [[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]]

max: 1.5792128155073915
min: -1.913280244657798


    Sqrt

In [195]:
# these dumb -ve values seems to be annoying, let's get rid of it
sqrt = np.sqrt(arr[arr > 0])
print("\nsquar .. oh by the way, do you know why four (4) was afraid? .. because it was too (2) scared .. ok never mind .. back to our code\n\nSqrt:", sqrt)


# or make some tricky stuff
# i will get the square root of the abs(arr), and then add a negative sign to the index where the arr was negative

# Getting the numpy array in a list
l = list(arr)
# this list is a list of lists .. each row is a list

# Getting the negative indexes as a list of tuples (tuples because this is a 2D array)
l_negative_indexes = []
for i in range(len(l)):
    for j in range(len(l[i])):
        if l[i][j] < 0:
            l_negative_indexes.append((i,j))
print("\n\n\nSecond way\nnegative indexes:")
print(l_negative_indexes)

# Getting the sqrt of the abs(arr)
sqrt_arr = np.sqrt(np.abs(arr))

# putting -ve sign before the indexes that were negative in the original arr
for i in l_negative_indexes:
    sqrt_arr[i[0]][i[1]] = -sqrt_arr[i[0]][i[1]]

# Printing the final result
print("\nsqrt:",sqrt_arr)



squar .. oh by the way, do you know why four (4) was afraid? .. because it was too (2) scared .. ok never mind .. back to our code

Sqrt: [0.70477951 0.80479099 1.23411096 1.25666734 0.87603352 0.73658675
 0.49189661 0.56057768]



Second way
negative indexes:
[(0, 1), (1, 0), (1, 1), (2, 0), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3), (4, 0), (4, 2), (4, 3)]

sqrt: [[ 0.70477951 -0.37183908  0.80479099  1.23411096]
 [-0.48389397 -0.48387701  1.25666734  0.87603352]
 [-0.68518201  0.73658675 -0.68074789 -0.68244396]
 [ 0.49189661 -1.38321374 -1.31336127 -0.74985834]
 [-1.00639511  0.56057768 -0.95290297 -1.18840385]]


    abs (is actually calculated but there it is)

In [196]:
print(np.abs(arr))

[[0.49671415 0.1382643  0.64768854 1.52302986]
 [0.23415337 0.23413696 1.57921282 0.76743473]
 [0.46947439 0.54256004 0.46341769 0.46572975]
 [0.24196227 1.91328024 1.72491783 0.56228753]
 [1.01283112 0.31424733 0.90802408 1.4123037 ]]


---

<br>

- ( **18** ) _What is the difference between np.dot() & np.multiply() & np.matmul._

In [197]:
import numpy as np
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[-1, 0], [-2, 4]])
# write your code here

# dot()

# multiply()

# matmul()

    Solution

- `np.dot( )` :<br> is a function in Numpy that computes the dot product between two arrays. The dot product operation multiplies the corresponding elements of the two arrays and sums up the products. If the two arrays are 1-D, it returns their inner product; if the arrays are 2-D, it returns matrix multiplication.

In [198]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

print(np.dot(a, b))
print()
print(np.matmul(matrix1,matrix2))

55

[[ -5   8]
 [-11  16]]


<br>

- `np.matmul( )` :<br> is a function in Numpy that performs matrix multiplication between two arrays. It implements matrix multiplication by following the rules of matrix algebra, which requires the number of columns in the first matrix to be equal to the number of rows in the second matrix.

In [199]:
print(np.matmul(matrix1,matrix2))

[[ -5   8]
 [-11  16]]


<br>

- `np.multiply( )` :<br> is a function in Numpy that performs element-wise multiplication between two arrays of the same shape. It multiplies each corresponding element of the input arrays to produce a new array with the same shape as the input arrays.

In [200]:
print(a)
print(b)
print()
print(np.multiply(a,b))
print("\n")

print(matrix1)
print(matrix2)
print()
print(np.multiply(matrix1,matrix2))

[1 2 3 4 5]
[1 2 3 4 5]

[ 1  4  9 16 25]


[[1 2]
 [3 4]]
[[-1  0]
 [-2  4]]

[[-1  0]
 [-6 16]]


---